services:
  postgres:
    image: 'postgres:18'
    environment:
      POSTGRES_DB: jobqueue
      POSTGRES_USER: jobqueue
      POSTGRES_PASSWORD: local
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql

  redis:
    image: 'redis:8'
    ports:
      - '6379:6379'

volumes:
  pgdata: